wrappers/nmake

```
root@ac06aa16deab:/opt/msvc/bin/x86# /bin/sh /opt/msvc/bin/x86/nmake
/opt/msvc/bin/x86/nmake: 3: /opt/msvc/bin/x86/nmake: Bad substitution
root@ac06aa16deab:/opt/msvc/bin/x86# /bin/bash /opt/msvc/bin/x86/nmake
Microsoft (R) Program Maintenance Utility Version 14.25.28612.0
Copyright (C) Microsoft Corporation.  All rights reserved.
NMAKE : fatal error U1064: MAKEFILE not found and no target specified
Stop.
root@ac06aa16deab:/opt/msvc/bin/x86# 
```

Use bash so substitutions work for "nmake"

---

wrappers/armasm
wrappers/armasm64
wrappers/cl
wrappers/cmd
wrappers/dumpbin
wrappers/lib
wrappers/link
wrappers/msvcenv.sh
wrappers/mt
wrappers/rc

This patch fixes the problem caused by #11 that the backslash
replacements in **msvcenv.sh** is not supported by _/bin/sh_. Considering that
the **nmake** wrapper has already been using _bash_, we changed all wrappers to use
_bash_ for consistency.
This patch is not yet tested from a clean build because of #12.

Modify all wrappers to use bash

---

wrappers/wine-msvc.sh

This PR uses the array feature in bash to preserve word splitting in `wine-msvc.sh`. An example assuming a suitable `cmake` wrapper is in place:
```
cmake -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RELWITHDEBINFO .
```
__Before:__ The word split would not be preserved when re-splitting the `ARGS` string in Line 19.
```
CMake Error: Could not create named generator NMake
[...]
```
__After:__ The word split is preserved.
There are several other possible solutions to this problem, but we feel using an array is the cleanest since we are using bash here. We also converted the script to follow the word split behavior of bash (e.g., not quoting in line 2 because bash does not split in normal variable assignments).
P.S. We are adding support for parallel compilation (start `mspdbsrv.exe` to …

Take care of word split concerns in wine-msvc.sh

---

vsdownload.py

Fixes the following error:
```
$ ./vsdownload.py --save-manifest
Fetching https://aka.ms/vs/16/release/channel
Got toplevel manifest for 16.6.4
Loaded installer manifest for 16.6.4
Traceback (most recent call last):
File "./vsdownload.py", line 505, in <module>
packages = getPackages(getManifest(args))
File "./vsdownload.py", line 150, in getManifest
f.write(manifestdata)
TypeError: write() argument must be str, not bytes
```
Signed-off-by: Juuso Alasuutari <juuso.alasuutari@gmail.com>

open() manifest savefile in binary mode to make it work with Python 3

---

Dockerfile

Helps see downloads as they happen and prevents cutting off in the middle of lines.

Don't buffer output during download.

---

vsdownload.py

compare the selection
```
git clone https://github.com/mstorsjo/msvc-wine
./msvc-wine/vsdownload.py --accept-license --print-selection > latest.txt
./msvc-wine/vsdownload.py --accept-license --print-selection --msvc-16.0 > msvc-16.0.txt
./msvc-wine/vsdownload.py --accept-license --print-selection --msvc-16.0 Microsoft.Windows.UniversalCRT.Msu.81 > msvc-16.0_pkg-selected.txt
diff msvc-16.0.txt latest.txt
diff msvc-16.0.txt msvc-16.0_pkg-selected.txt
```
1. Looks like the default packages are needlessly downloaded if an MSVC toolchain was selected and no packages were selected.
2. `setPackageSelectionMSVC15()` and `setPackageSelectionMSVC16()` have the code to add `defaultPackages` to `args.package` if the selected MSVC toolchain version was not found.

vsdownload.py - setPackageSelection() sets defaults too early?

---

vsdownload.py

Tested with `Python 3.9.9`.
The problem doesn't appear with `Python 2.7.18`.
```
git clone https://github.com/mstorsjo/msvc-wine
./msvc-wine/vsdownload.py --accept-license --print-version --save-manifest
./msvc-wine/vsdownload.py --accept-license --print-version --save-manifest --manifest=16.11.9.manifest
```
After the last command the program prints the message:
```
Old saved manifest in "16.11.9.manifest" differs from newly downloaded one, not overwriting!
```
The local manifest differs when compared to itself.
Alternatively, the problem can be fixed by opening the old manifest in binary mode but I'm not sure if it doesn't break stuff under certain conditions.

vsdownload.py - with "--save-manifest" read the old manifest in binary mode

---

vsdownload.py

The problem: lines printed from async function `_downloadPayload()` sometimes don't appear in the output.
The problem and the results of the tests are the same with both `Python 3.9.9` and `Python 2.7.18`.
```
git clone https://github.com/mstorsjo/msvc-wine.git
```
Get the manifest.
```
./msvc-wine/vsdownload.py --accept-license --save-manifest --print-version
```
Store the download command in a variable because it will be used a lot.
```
VSDOWNLOADCMD="\
./msvc-wine/vsdownload.py --accept-license --manifest=16.11.9.manifest --cache=cache --only-download \
Microsoft.CodeAnalysis.ExpressionEvaluator \
Microsoft.DiaSymReader \
Microsoft.DiagnosticsHub.CpuSampling \
Microsoft.DiagnosticsHub.CpuSampling.ExternalDependencies \
Microsoft.DiagnosticsHub.CpuSampling.Resources \ …
```

vsdownload.py - Use six.print_(flush=True) in async function

---

wrappers/msvcenv.sh

Change `$0` to read the executed source location to `${BASH_SOURCE[0]}`, as the former code would not work in the case of sourcing the script because `$0` will have the value of the sourcer script.
This Stack Overflow answer thoroughly explains the difference between `$0` and `${BASH_SOURCE[0]}`: https://stackoverflow.com/a/35006505, as well as the linked answer within the above answer: https://stackoverflow.com/a/29835459.

Change "$0" to read the executed source location to "${BASH_SOURCE[0]}

---

install.sh

This symlinks some subdirs instead of renaming them and makes sure there is a "Windows Kits" directory.

Changes to install to make it work with clang-cl /winsysroot by default

---

vsdownload.py

The script can actually be useful to download VS on Windows too. When doing so, use the Windows-native msiexec tool to extract the MSIs, instead of msiextract.
And because of how open files are handled on Windows, use a context manager for the subprocess.check_call output, so that if it throws an exception, the file is not left open.

Allow to use vsdownload on Windows

---

wrappers/wine-msvc.sh

This should silence all wine debug messages, instead of just filtering out some of them.
If building with MSVC with /showDependencies, the output from /showIncludes gets printed on stderr instead of stdout, and then wine debug messages may get intermixed with the /showIncludes output, breaking dependency handling.
CC @huangqinjin - does this work for you?

Execute wine wrapped commands with WINEDEBUG=-all

---

wrappers/wine-msvc.bat
wrappers/wine-msvc.sh

A single wine invocation may spawn several long-living Win32 processes automatically. These processes will inherit at least the stderr handle of current wine command and keep it open. Waiting for the wine command's stderr will hang, e.g. CMake waits for the compilation commands: https://gitlab.kitware.com/cmake/cmake/-/blob/0991023c30ed5b83bcb1446b5bcc9c1eae028835/Source/kwsys/ProcessUNIX.c#L1076
Fixes https://github.com/mstorsjo/msvc-wine/issues/47

Fix hang-up issue

---

wrappers/mt
wrappers/wine-msvc.bat

CMake invokes mt.exe with the undocumented option, and mt.exe may exit with 0x41020001.
The exit code is truncated to 8 bits on POSIX hosts.
Translate exit code of mt.exe in bat file.
https://gitlab.kitware.com/cmake/cmake/-/blob/0991023c30ed5b83bcb1446b5bcc9c1eae028835/Source/cmcmd.cxx#L2533
https://gitlab.kitware.com/cmake/cmake/-/blob/0991023c30ed5b83bcb1446b5bcc9c1eae028835/Source/cmcmd.cxx#L2388
Fixes https://github.com/mstorsjo/msvc-wine/issues/45

Handle /notify_update in mt wrapper

---

wrappers/wine-msvc.bat
wrappers/wine-msvc.sh

1. Escape all double-quotes.
2. EnableDelayedExpansion for other special characters: %^&|<>
Exclamation mark ! is not handled correctly by wine cmd currently.
https://bugs.winehq.org/show_bug.cgi?id=54928

Fix bat file arguments handling

---

test/test-cl.sh
test/test-dumpbin.sh
test/test.sh
wrappers/cl
wrappers/wine-msvc.sh

- Unixify paths for cl /showIncludes only. Otherwise outputs may be _partially_ converted, e.g.
```shell
> echo '__FILE__;' > /tmp/test.c && /opt/msvc/bin/x64/cl /nologo /E /FC /tmp/test.c
test.c
#line 1 "\\tmp\\test.c"
"\\tmp\\test.c";
```
- Unixify paths for dumpbin /PDBPATH also. Otherwise outputs were also _partially_ converted, e.g.
```
> echo 'int main() {}' > /tmp/main.c && /opt/msvc/bin/x64/cl /nologo /Z7 /tmp/main.c /Fe/tmp/main.exe && /opt/msvc/bin/x64/dumpbin /nologo /PDBPATH /tmp/main.exe
main.c
Dump of file \tmp\main.exe
File Type: EXECUTABLE IMAGE
PDB file found at '\tmp\main.pdb'
```
Vcpkg use it to implement the script `vcpkg_copy_pdbs`: https://github.com/microsoft/vcpkg/blob/662dbb50e63af15baa2909b7eac5b1b87e86a0aa/scripts/cmake/vcpkg_copy_pdbs.cmake#L24
- Unixify paths …

Unixify paths for more cases

---

wrappers/wine-msvc.sh

CC @huangqinjin 
This helps fixing compiling LLVM with msvc-wine with recent Wine versions (Wine 8.1 or newer affected) - see https://bugs.winehq.org/show_bug.cgi?id=55200 for details.

wrappers: Document adding z: prefixes on absolute paths, add z: prefixes in one more case

---

.github/workflows/build.yml
test/meson.build
test/test-meson.sh
test/test.sh

Only testing building with MSVC - not testing building with clang-cl with Meson. Clang-cl does work with Meson, but for the resource compiler, Meson currently fails to detect llvm-rc.
Therefore, currently if building with Meson, one has to use the Wine wrapped version of rc.exe, which requires Wine to be available, contrary to the rest of the clang-cl/lld based setup. (The CI environment for the clang/lld tests intentionally does not have Wine available.)

test: Test building Meson based projects with msvc-wine

---

test/test-asm.sh
test/test.sh

Just testing that running the assembler exits successfully.
Adding the testing in test-cl.sh, instead of a separate test script, although I'm open to creating a separate test script if that's preferred.
CC @huangqinjin

test: Add testing of the arch specific assembler tools

---

test/test-meson.sh

Meson doesn't use the /FS option when generating PDB debug info, which means that it doesn't use mspdbsrv.exe. Thus, the default debug mode should work fine on macOS too.

test: Remove a special case for Meson testing on macOS

---

.github/workflows/projects.yml

CC @huangqinjin 
This integrates testing of three real world projects that can be compiled with msvc-wine; dav1d (using Meson), which builds in 4 minutes in total (including installing msvc-wine) on Github Actions, ffmpeg (using a custom make based build system), which builds in 30 minutes, and llvm (which uses cmake), which builds in 3h 30min.
Including the full llvm testcase is most probably overkill, but on the other hand, it serves as a great reference testcase. (It also manages to trigger certain rare bugs, see #78.) Ffmpeg with 30 minutes is also significantly slower than the rest of the test cases we have. Dav1d with 4 minutes is quite tolerable on the other hand, but I'm not sure how much extra test coverage it adds on top of #79 and #80.
Not sure what the best way forward would …

RFC: test: Add github actions tests for building real world projects with msvc-wine

---

wrappers/cl

Before:
https://github.com/mstorsjo/msvc-wine/actions/runs/7160678650/job/19503276835#step:5:322
https://github.com/mstorsjo/msvc-wine/actions/runs/7160678650/job/19503276563#step:5:322
After:
https://github.com/mstorsjo/msvc-wine/actions/runs/7223373226/job/19682291627?pr=98#step:5:322
https://github.com/mstorsjo/msvc-wine/actions/runs/7223373226/job/19684065015?pr=98#step:5:322
Such that the file paths become clickable in VS Code.

Unixify paths for cl warnings and errors

---

install.sh

install.sh detects the WinSDK version by scanning the common ./kits/10/include/ directory, but other kits such as WDK add non-versioned directories there, for example ./kits/10/include/wdf/.
Use a more narrow glob expression to ignore these extra directories.
Remove a redundant SDK version variable assignment and print the detected SDK and MSCV versions for diagnostics.

Fortify WinSDK version detection in install.sh

---

.github/workflows/build.yml
test/test-cmake.sh
test/test-mt.sh

mt.exe no longer crashes on macOS with Wine 9.0.
macOS-12 runner image version 20240119 has updated to Wine 9.0.
https://github.com/huangqinjin/msvc-wine/actions/runs/7583317817/job/20752571482
Let's wait until most runners have been upgraded.

test: Enable mt.exe on macOS with Wine 9.0

---

Dockerfile
Dockerfile.hello
install.sh
wrappers/wine-msvc.sh

Try using `wine64` then fall back `wine`; this should close #99 (and not introduce regressions for cases like #30).

Try using `wine64` then fall back to `wine`

---

wrappers/msbuild

Set a global MSBuild property to always prefer 64-bit build tools.
Reference:
https://learn.microsoft.com/en-us/cpp/build/reference/msbuild-visual-cpp-overview?view=msvc-170#preferredtoolarchitecture-property
Resolves #108

msbuild: Prefer x86_64 build tools for all targets

---

.github/workflows/build.yml

This reverts commit 26d574b051ddf4642cf92fb92e921c0561196b8a.
Running `brew update` breaks macos-12 runner version 20240202.
It was needed at that moment to get latest wine 9.0 but now it is no longer needed.

Revert "github: Run brew update to get latest softwares"

---

.github/workflows/build.yml
install.sh
test/test-wdk-msbuild.sh
test/test.sh
test/wdk/test.c
test/wdk/test.inx
test/wdk/test.vcxproj
vsdownload.py
wdk-download.sh
wrappers/msbuild
wrappers/msvcenv.sh

Add a new command line option '--with-wdk-installers' pointing to the directory where the MSI packages downloaded by `wdksetup.exe` are located.
Extract the WDK packages after unpacking the Windows SDK packages.
They both install files in the same versioned directories.
Unpack the included VS extension files onto the MSVC tree.
Fix the WDK directory structure after extracting MSI packages with `msiextract` on Linux.
Resolves https://github.com/mstorsjo/msvc-wine/issues/28

RFC: Add basic support for automated WDK installation

---

.github/workflows/build.yml
.github/workflows/projects.yml
Dockerfile
README.md
vsdownload.py

Python 3 style print functions are already used throughout the codebase, and only a few places use six.
Python 2 compatibility is not longer there.
Use the standard `json` module in place of `simplejson`.

Drop unmaintained Python 2 support via six

---

fixinclude
test/headers.cpp

This style is present in gdiplus.h.
This should hopefully fix #123.

fixinclude: Match include lines with leading spaces

---

install.sh
test/CMakeLists.txt
test/hello.cpp
test/test-cmake.sh

https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9337
The coming cmake 3.30 supports `import std` for clang and MSVC.
For MSVC, it need to locate `modules.json` which is in `${VCToolsInstallDir}/modules` (`VCToolsInstallDir = VC/Tools/MSVC/$VER`). https://gitlab.kitware.com/cmake/cmake/-/blob/ca449572ef8b1c6066e88879795900aea9727834/Modules/Compiler/MSVC-CXX-CXXImportStd.cmake#L2-11
```cmake
find_file(_msvc_modules_json_file
NAME modules.json
HINTS
"$ENV{VCToolsInstallDir}/modules"
PATHS
"$ENV{INCLUDE}"
"${CMAKE_CXX_COMPILER}/../../.."
PATH_SUFFIXES
../modules
NO_CACHE)
```
To support `import std` without those environment variables presets, the specific directory layout is required. There are two ways going on:
1. Copy `${VCToolsInstallDir}/modules/*` to installation root. There …

Support `import std` for CMake

---

install.sh
vsdownload.py

So that the dest dir is valid for clang /winsysroot without installation on Unix and Windows.

vsdownload: kits -> Windows Kits

---

vsdownload.py

vsdownload: Handle machineArch dependency constraint

---

vsdownload.py

Depends on #140.
```
"Microsoft.VisualCpp.Tools.HostARM64.TargetX64"
"Microsoft.VisualCpp.Tools.HostARM64.TargetX86"
"Microsoft.VisualCpp.Tools.HostX64.TargetX64"
"Microsoft.VisualCpp.Tools.HostX64.TargetX86"
```
I think it is pretty safe to skip packages if their ids do not match host arch.
[PR #140](https://github.com/mstorsjo/msvc-wine/actions/runs/11194999176/job/31122154650?pr=140#step:4:49)
```
Selected 544 packages, for a total download size of 2.9 GB, install size of 8.9 GB
```
[PR #148](https://github.com/mstorsjo/msvc-wine/actions/runs/11195105784/job/31122372211?pr=148#step:4:49)
```
Selected 475 packages, for a total download size of 2.7 GB, install size of 8.5 GB
```

vsdownload: Add an option to skip packages that do not match host arch

---

vsdownload.py

Depends on #148.
[PR #148](https://github.com/mstorsjo/msvc-wine/actions/runs/11198692222/job/31130172974?pr=148#step:4:49)
```
Selected 475 packages, for a total download size of 2.7 GB, install size of 8.5 GB
```
[PR #149 matching host arch exactly](https://github.com/mstorsjo/msvc-wine/actions/runs/11258538861/job/31305372957?pr=149)
```
Selected 449 packages, for a total download size of 2.5 GB, install size of 8.2 GB
```
**EDIT**: We go *matching host arch exactly*.
~~[PR #149](https://github.com/mstorsjo/msvc-wine/actions/runs/11202379694/job/31138414515?pr=149#step:4:49)~~
~~Selected 463 packages, for a total download size of 2.6 GB, install size of 8.3 GB~~
~~Current implementation apply the knownledge that~~
1. x64 host can run x86 binaries
1. arm64 host can run x86/x64 binaries …

vsdownload: Filter packages based on their arch information

---

wrappers/msbuild

Define yet more environment variables to make the platform SDK search methods work without the Windows Registry.

wrappers(msbuild): Define the SDK search root paths

---

test/test-vcpkg.sh

Upstream commit https://github.com/microsoft/vcpkg/commit/6dbc951463b07484d165415667a8f65feda7fbf4 broke PDB installation on non-Windows.

test: Disable testing vcpkg's PDB installation function

---

test/test-vcpkg.sh

This reverts commit e3c35c04379ab641dc72cc09bbe3f9ef2d74d44c.
Upstream commit https://github.com/microsoft/vcpkg/commit/6ae3ccc87c3617b06ac1578ef9b9944f1bb8a373 made PDB installation on non-Windows work again.

Revert "test: Disable testing vcpkg's PDB installation function"

---

vsdownload.py

Observed that starting with VS 17.12, package `Microsoft.VisualStudio.PackageGroup.VsDevCmd` is missing
https://github.com/mstorsjo/msvc-wine/actions/runs/11948558852/job/33306358321#step:4:42, compared to VS 17.11
https://github.com/mstorsjo/msvc-wine/actions/runs/11427400934/job/31791489553#step:4:39.
Checked dependencies with their manifests,
- 17.11:
```
Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core
Microsoft.VisualStudio.PackageGroup.VC.CoreIDE.Reduced
Microsoft.VisualStudio.PackageGroup.Core
Microsoft.VisualStudio.PackageGroup.CoreEditor
Microsoft.VisualStudio.PackageGroup.VsDevCmd
```
- 17.12:
```
Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core …
```

vsdownload: Use id in dependencies if exists

---

vsdownload.py

Observed that `MSBuild` casing is not consistent, e.g. package `Microsoft.VisualStudio.StaticAnalysis.auxil` contains
```
Contents/Msbuild/Microsoft/VC/v170/fxcop.xml
Contents/MSBuild/Microsoft/VisualStudio/v17.0/CodeAnalysis/fxcoptask.dll
```
What we get finally depends on the extracting order of packages, we may get `MSBuild`, `Msbuild` or even both. This workaround make sure we get `MSBuild`, because `mergeTrees` will merge any casing into the existing `MSBuild` folder.

vsdownload: Workaround for inconsistent MSBuild folder casing when extracting packages

---

install.sh

This makes clang-cl use of e.g. atlbase.h work on case sensitive file systems (as atlbase.h originally includes OleCtl.h), and makes MSVC use of atlbase.h produce dependency files that don't require files to be rebuilt every time.
This should fix #167.
CC @vid512

install: Make ATL headers use consistent lower case includes of other headers

---

vsdownload.py

Previously `--only-host` didn't accept any argument. Now user can explicitly specify `yes` or `no`.
```shell
$ ./vsdownload.py -h
--only-host [yes|no]  Only download packages that match host arch (default: yes)
```

vsdownload: Fix unable to set `--only-host` to False

---

vsdownload.py

ASAN is great. It must be included!
For versionless toolchains, package `Microsoft.VisualCpp.ASAN.X86` is already a dependency of `Microsoft.VisualStudio.Workload.VCTools`.

vsdownload: Install ASAN along with MSVC

---

.github/workflows/build.yml

Switch the Linux CI workflow back to `ubuntu-latest`.
Update `wine-mono` to version 8.1.0 as instructed in
https://gitlab.winehq.org/wine/wine/-/wikis/Wine-Mono#versions
Resolves #172

github: Update `wine-mono` to v8.1.0 on Ubuntu 24.04

---

.github/workflows/build.yml

This reverts commit a40dd807ceaa189783766c447ea2c67b0d68f588.
Wine 10.0 bundled with Wine Mono 9.4.0, is now available on github macOS runners.

Revert "github: Install Wine Mono 9.0 for macOS"

---

.github/workflows/build.yml

Reverts #182 due to macOS runners upgrade got reverted by https://github.com/actions/runner-images/pull/11700.

Revert "Revert "github: Install Wine Mono 9.0 for macOS""

---

vsdownload.py

Previously, we'd end up downloading both the default SDK from the manifest, and the SDK that was default for that version of MSVC.
Then install.sh would pick the latest SDK out of the ones installed, which wouldn't be the right choice when we explicitly wanted an older one.
If selecting an implicit default SDK via --msvc-version, set this as the option as if set via --sdk-version, which forces other SDKs to be ignored.

vsdownload: Only download the right SDK for MSVC 16/17 with --msvc-version
